### PR TITLE
Match line numbers of output .lua with input .tl

### PR DESCRIPTION
**Pull request by hishamhm**
This makes a big difference when debugging, as the line numbers presented by the traceback in runtime errors actually match those in your code.

This is the strategy I took:

* first, `tlparser.lua` was extended so that it annotates `.lin` and `.col` in each ast node. It still uses `lineno` as a helper function (which traverses the input file every time), so this is inefficient, but easy to fix (if the lin/col of all AST nodes are increasing if you traverse them in-order).
* then, I removed all explicit generations of `"\n"` from `tlcode.lua`. As each statement in a block is generated, the current line is checked against the line of the AST node, and the necessary amount of linefeeds are generated. It is a very simple strategy (I only had to modify one function of the code generator) but it works really well. Since I'm not checking _every_ AST node (only statements in blocks) it will probably give some errors in code that's formatted in funny ways (like @fsantanna sometimes likes to write :) ) but it will resync back to the right linecount in the next statement. I thought this was worth the implementation simplicity. If necessary, `resync_line` calls can be added in other places.
* since I needed to propagate more formatting-related information in the `tlcode.lua` traversal, I changed `i` to `fmt` (a table including `.indent` and `.line`), instead of adding a new argument. (The diff would be way smaller if I kept it called `i` but I thought that would be confusing.)
* as a bonus, now that AST nodes are annotated with `.lin` and `.col`, there's no need to call `lineno` in tlchecker anymore, but I didn't implement that (yet?).

As a downside, this will break many expected outputs in your `test.lua` test suite...

### CODE REVIEW

**Comment by hishamhm** [comment]
Also, if this one is included, I have another one that changes the output from foo["bar"] to foo.bar whenever it's safe to do so. With these two changes, my output files look remarkably similar to the input files (except for the lack of comments).

**Comment by hishamhm** [comment]
BTW, if you want to play with pull requests before merging them, you can check them out from my repo according to the branch name that shows up there. In this case, just go to a blank directory and:

```
git clone https://github.com/hishamhm/typedlua --branch line-numbers
```

**Comment by andremm** [comment]
Cool! Thanks for the pull request! I really liked your proposal, but I just hadn't the time to update the tests before merging it.  Can you also add the change from `foo["bar"]` to `foo.bar` too? I think it would be better to merge both at the same time. :)

**Comment by hishamhm** [comment]
Ok, will do!

**Comment by hishamhm** [comment]
Done, I uploaded the change from `foo["bar"]` to `foo.bar`. No hurries about this pull request. I'll keep maintaining it in sync with the master branch while I use typedlua.

**Comment by hishamhm** [comment]
Thanks!!

Ah! Just so you know: the one situation where the output code looks weird is in long tables, because `{x,y,z,...}` is always going in a single line (because it's resyncing only at statement intervals). It might be a good idea to add a `resync_line` call in `code_fieldlist` as well in the future. But I'm happy enough with the error messages for now!

**Pull request merged**
